name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2  # Checks out your code

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Specifies the Node.js version

    - name: Install dependencies
      run: npm install  # Installs dependencies

    - name: Run tests
      run: npm test  # Runs tests using the test script in package.json
